mainApp.controller("editProfileCtrl",['$scope','$location','mainUrl','townData','userProfile',function($scope,$location,mainUrl,townData,userProfile){
    userProfile.getUserData(function(resp){
        $scope.currentUser=resp;
    }),
    townData.getAllTowns(function(resp){
        $scope.townsData=resp;
    }),
    $scope.updateProfile=function(user){
        userProfile.editUserData(user);
        $location.path('/');
    },
    $scope.changePassword=function(user){
        userProfile.changePass(user);
        $location.path('/');
    }
    $scope.cancel=function(){
        $location.path('/');
    }
}])