mainApp.controller("MainController",function($scope,mainData){
    mainData.getAllAds(function(resp){
        $scope.adsData=resp;
    }),
    mainData.getAllTowns(function(resp){
        $scope.townsData=resp;
    }),
    mainData.getAllCategory(function(resp){
        $scope.categoryData=resp;
    })
})