mainApp.factory('mainData',['mainUrl','$http',function(mainUrl,$http){
    return {
        getAllAds:function(success){
           // categoryId==null?"CategoryId"+categoryId:"";
            //townId==null?"townId"+townId:"";
            $http({method:'GET',url:mainUrl+'ads?Pagesize=10&startpage=1'})
                .success(function(data,status,headers,config){
                    success(data);
                })
                .error(function(data,status,headers,config){
                    $log.warn(data);
                })
        },
        getAllTowns:function(success){
            $http({method:'GET',url:mainUrl+'towns'})
                .success(function(data,status,headers,config){
                    success(data);
                })
                .error(function(data,status,headers,config){
                    $log.warn(data);
                })
        },
        getAllCategory:function(success){
            $http({method:'GET',url:mainUrl+'categories'})
                .success(function(data,status,headers,config){
                    success(data);
                })
                .error(function(data,status,headers,config){
                    $log.warn(data);
                })
        }
    }
}])